# Generated by Django 3.0 on 2023-06-24 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='email',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(default=12345, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
