# Generated by Django 3.0 on 2023-07-02 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20230625_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='management.Manager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='discription',
            field=models.TextField(blank=True),
        ),
    ]
