# Generated by Django 3.0 on 2023-07-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_mealimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Manager'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Manager'),
        ),
        migrations.AlterField(
            model_name='table',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Manager'),
        ),
    ]
