# Generated by Django 3.0 on 2023-07-10 06:57

from django.db import migrations, models
import management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20230703_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealimage',
            name='image',
            field=models.ImageField(upload_to='managment/images', validators=[management.validators.validate_file_size]),
        ),
    ]
