# Generated by Django 3.0 on 2023-07-16 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20230710_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='discription',
            field=models.TextField(blank=True),
        ),
    ]
