# Generated by Django 3.0 on 2023-07-16 07:11

from django.db import migrations, models
import django.db.models.deletion
import management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20230716_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealimage',
            name='image',
            field=models.ImageField(upload_to='managment/meal_image', validators=[management.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='mealimage',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_image', to='management.Meal'),
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='managment/re_image', validators=[management.validators.validate_file_size])),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_image', to='management.Restaurant')),
            ],
        ),
    ]
