# Generated by Django 3.0 on 2023-07-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20230716_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealimage',
            old_name='image',
            new_name='mealimage',
        ),
        migrations.RenameField(
            model_name='restaurantimage',
            old_name='meal',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='restaurantimage',
            old_name='image',
            new_name='restaurantimage',
        ),
    ]
