# Generated by Django 3.0 on 2023-07-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20230716_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealimage',
            old_name='mealimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='restaurantimage',
            old_name='restaurantimage',
            new_name='image',
        ),
    ]
