# Generated by Django 3.0 on 2023-07-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20230716_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='manager',
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.Restaurant'),
            preserve_default=False,
        ),
    ]
