# Generated by Django 3.0 on 2023-07-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20230717_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='management.Restaurant'),
        ),
    ]
