# Generated by Django 3.0 on 2023-07-31 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20230727_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='manager',
        ),
        migrations.AddField(
            model_name='meal',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='management.Restaurant'),
        ),
    ]
