# Generated by Django 3.0 on 2023-08-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_delete_favoritemeal'),
        ('management', '0016_auto_20230731_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Customer')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Meal')),
            ],
        ),
    ]
