# Generated by Django 3.0 on 2023-08-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_delete_favoriterestaurant'),
        ('management', '0017_favoritemeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemeal',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FavoriteRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Customer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Restaurant')),
            ],
        ),
    ]
