# Generated by Django 3.0 on 2023-08-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20230802_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='restaurant',
            new_name='simplerestaurant',
        ),
    ]
