# Generated by Django 3.0 on 2023-08-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_auto_20230802_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='simplerestaurant',
            new_name='restaurant',
        ),
    ]
