# Generated by Django 3.0 on 2023-08-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20230802_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterestaurant',
            name='like',
            field=models.BooleanField(verbose_name=True),
        ),
    ]
