# Generated by Django 3.0 on 2023-08-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20230804_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterestaurant',
            name='like',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
