# Generated by Django 3.0 on 2023-08-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_auto_20230804_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemeal',
            name='like',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
