# Generated by Django 3.0 on 2023-08-09 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_auto_20230808_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='reservation',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='management.Reservation'),
            preserve_default=False,
        ),
    ]
