# Generated by Django 3.0 on 2023-08-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_auto_20230809_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Reservation'),
        ),
    ]
