# Generated by Django 3.0 on 2023-08-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_auto_20230809_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
