# Generated by Django 3.0 on 2023-08-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_meal_average_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='average_rating',
            new_name='rating',
        ),
    ]
