# Generated by Django 3.0 on 2023-08-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_auto_20230811_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='rating',
            new_name='average_rating',
        ),
    ]
