# Generated by Django 3.0 on 2023-08-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_auto_20230811_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolve', models.BooleanField(default=True, editable=False)),
                ('message', models.TextField()),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Manager')),
            ],
        ),
    ]
