# Generated by Django 3.0 on 2023-08-12 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_auto_20230811_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_rent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('additional_thing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Meal')),
                ('reservstion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Reservation')),
            ],
        ),
    ]
