# Generated by Django 3.0 on 2023-08-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_reservationitem_tablebill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationitem',
            old_name='reservstion',
            new_name='reservation',
        ),
    ]
