# Generated by Django 3.0 on 2023-08-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolve',
            field=models.BooleanField(default=False),
        ),
    ]
