# Generated by Django 3.0 on 2023-08-11 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0032_auto_20230811_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='manager',
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
