# Generated by Django 3.0 on 2023-08-12 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_auto_20230812_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationitem',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Reservation'),
        ),
    ]
