# Generated by Django 3.0 on 2023-08-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_auto_20230812_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='management.Reservation'),
        ),
    ]
