# Generated by Django 3.0 on 2023-08-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_auto_20230811_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='average_rating',
        ),
    ]
