# Generated by Django 3.0 on 2023-08-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_auto_20230810_1518'),
        ('management', '0035_remove_meal_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='management.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Customer')),
            ],
        ),
    ]
