# Generated by Django 3.0 on 2023-08-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='customer',
        ),
    ]
