# Generated by Django 3.0 on 2023-08-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_auto_20230812_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
