# Generated by Django 3.0 on 2023-08-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_meal_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='average_rating',
        ),
    ]
