# Generated by Django 3.0 on 2023-08-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_auto_20230812_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='management.Meal'),
        ),
        migrations.AlterField(
            model_name='ratingrestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='management.Restaurant'),
        ),
    ]
