# Generated by Django 3.0 on 2023-08-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_reservation_restaurant'),
        ('management', '0041_auto_20230812_1618'),
    ]

    operations = [
    ]
