# Generated by Django 3.0 on 2023-08-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_merge_20230813_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
