# Generated by Django 3.0 on 2023-08-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_merge_20230813_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmeal',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], null=True),
        ),
    ]
