# Generated by Django 3.0 on 2023-08-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_auto_20230813_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebill',
            name='additional_thing',
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.Reservation'),
        ),
    ]
