# Generated by Django 3.0 on 2023-08-13 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_auto_20230813_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationitem',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Meal'),
        ),
    ]
