# Generated by Django 3.0 on 2023-08-13 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_auto_20230813_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
