# Generated by Django 3.0 on 2023-08-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_auto_20230813_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebill',
            name='table_rent',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
