# Generated by Django 3.0 on 2023-08-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_auto_20230813_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableBill',
        ),
    ]
