# Generated by Django 3.0 on 2023-08-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_delete_tablebill'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table_rent',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
