# Generated by Django 3.0 on 2023-08-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_auto_20230813_1316'),
        ('management', '0049_reservation_table_rent'),
    ]

    operations = [
    ]
