# Generated by Django 3.0 on 2023-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0051_deliverybill_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
