# Generated by Django 3.0 on 2023-08-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0052_reservation_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table_rent',
            field=models.FloatField(null=True),
        ),
    ]
