# Generated by Django 3.0 on 2023-08-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0054_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_rent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
