# Generated by Django 3.0 on 2023-06-05 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('person_phone', models.CharField(max_length=255)),
                ('date_of_reservation', models.DateField()),
                ('time_of_reservation', models.TimeField()),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Table')),
            ],
        ),
        migrations.CreateModel(
            name='TableBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_rent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extra_thing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.Bill')),
                ('reservstion_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField()),
                ('time_of_order', models.TimeField()),
                ('carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_rent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.Bill')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.Order')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='meals',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.Order'),
        ),
    ]
