# Generated by Django 3.0 on 2023-07-10 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_of_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_of_order',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
