# Generated by Django 3.0 on 2023-07-10 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20230710_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='meal_id',
            new_name='meal',
        ),
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='services.Order'),
        ),
    ]
