# Generated by Django 3.0 on 2023-07-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20230710_0957'),
        ('services', '0008_auto_20230710_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='OrderItem',
        ),
    ]
