# Generated by Django 3.0 on 2023-07-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20230717_2149'),
        ('services', '0011_auto_20230715_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Customer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Customer')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Meal')),
            ],
        ),
    ]
