# Generated by Django 3.0 on 2023-08-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_favoritemeal_favoriterestaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteMeal',
        ),
    ]
