# Generated by Django 3.0 on 2023-08-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_delete_favoritemeal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteRestaurant',
        ),
    ]
