# Generated by Django 3.0 on 2023-08-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_delete_favoriterestaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='person_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='person_phone',
        ),
    ]
