# Generated by Django 3.0 on 2023-08-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20230807_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date_of_reservation',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='table_number',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time_of_reservation',
            new_name='time',
        ),
    ]
