# Generated by Django 3.0 on 2023-08-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20230807_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
