# Generated by Django 3.0 on 2023-08-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_reservation'),
        ('services', '0017_reservation_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebill',
            name='reservstion_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Reservation'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
