# Generated by Django 3.0 on 2023-08-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20230808_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablebill',
            old_name='reservstion_id',
            new_name='reservstion',
        ),
    ]
