# Generated by Django 3.0 on 2023-08-10 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20230808_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverybill',
            old_name='order_id',
            new_name='order',
        ),
    ]
