# Generated by Django 3.0 on 2023-08-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20230810_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverybill',
            name='detail',
        ),
    ]
