# Generated by Django 3.0 on 2023-08-10 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_remove_deliverybill_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebill',
            name='detail',
        ),
        migrations.AddField(
            model_name='deliverybill',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
