# Generated by Django 3.0 on 2023-08-11 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_auto_20230811_1557'),
        ('services', '0022_auto_20230810_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablebill',
            old_name='extra_thing',
            new_name='additional_thing',
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Meal')),
                ('reservstion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Reservation')),
            ],
        ),
    ]
