# Generated by Django 3.0 on 2023-08-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20230811_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebill',
            name='reservstion',
        ),
        migrations.DeleteModel(
            name='ReservationItem',
        ),
        migrations.DeleteModel(
            name='TableBill',
        ),
    ]
