# Generated by Django 3.0 on 2023-08-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_auto_20230812_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='DeliveryBill',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
